import button from './Button/index.story';
import backButton from './BackButton/index.story';
import center from './Center/index.story';
import checkbox from './Checkbox/index.story';
import comboBox from './ComboBox/index.story';
import dateInput from './DateInput/index.story';
import form from './Form/index.story';
import formCard from './FormCard/index.story';
import formPage from './FormPage/index.story';
import home from './Home/index.story';
import horzForm from './HorzForm/index.story';
import input from './Input/index.story';
import link from './Link/index.story';
import list from './List/index.story';
import logo from './Logo/index.story';
import message from './Message/index.story';
import messagePage from './MessagePage/index.story';
import page from './Page/index.story';
import phoneInput from './PhoneInput/index.story';
import select from './Select/index.story';
import spacer from './Spacer/index.story';
import text from './Text/index.story';
import title from './Title/index.story';
import stages from './Stages/index.story';
import progressBar from './ProgressBar/index.story';
import box from './Box/index.story';
import radio from './Radio/index.story';
import avatarInput from './AvatarInput/index.story';
import imageInput from './ImageInput/index.story';
import imagesInput from './ImagesInput/index.story';
import modal from './Modal/index.story';
import modalPreview from './ModalPreview/index.story';
import multiUploader from './MultiUploader/index.story';
import preview from './Preview/index.story';
import slider from './Slider/index.story';
import notice from './Notice/index.story';
import dropzone from './Dropzone/index.story';
import noticeButton from './NoticeButton/index.story';
import loading from './Loading/index.story';

export default () => {
  const base = 'common';

  button(base);
  backButton(base);
  center(base);
  checkbox(base);
  comboBox(base);
  dateInput(base);
  form(base);
  formCard(base);
  formPage(base);
  home(base);
  horzForm(base);
  input(base);
  link(base);
  list(base);
  logo(base);
  message(base);
  messagePage(base);
  page(base);
  phoneInput(base);
  select(base);
  spacer(base);
  text(base);
  title(base);
  stages(base);
  progressBar(base);
  box(base);
  radio(base);
  avatarInput(base);
  imageInput(base);
  imagesInput(base);
  modal(base);
  modalPreview(base);
  multiUploader(base);
  preview(base);
  slider(base);
  notice(base);
  noticeButton(base);
  dropzone(base);
  loading(base);
};
